const suffix='gpt6-astra-pro-mcp-colabdev',name='likeness95-100-'+suffix;
const asset=p=>import.meta.env.BASE_URL+p.replace(/^\/+/, '');
export function installCampaignStatus(){
 const section=document.createElement('section');section.className='campaign-panel';section.id='visual-campaign';section.innerHTML='<div class="campaign-heading"><div><span class="eyebrow">EDITED · RENDERED · VISUALLY REVIEWED</span><h3>Character refinement.</h3></div><a class="campaign-ledger" href="'+asset('/progress/'+name+'/ledger.json')+'">Evidence ledger +</a></div><div class="campaign-metrics"></div><p class="campaign-note"></p><div class="campaign-latest"></div><details class="campaign-history"><summary>All reviewed candidates and comparison sheets</summary><div class="campaign-sheets"></div><div class="campaign-reviews"></div></details>';
 const archive=document.createElement('a');archive.className='campaign-archive';archive.href=asset('/exports/campaign-evidence-'+suffix+'.tar.gz');archive.textContent='Download all reviewed states and render evidence +';archive.setAttribute('download','');
 const location=document.createElement('code');location.className='campaign-archive-path';location.textContent='/home/dev/project/3d/campus-portrait-'+suffix+'/.output/campaign-evidence-'+suffix+'.tar.gz';
 section.querySelector('.campaign-note').after(archive,location);
 const cards=document.querySelector('#file-cards');cards.after(section);let stamp='';
 async function refresh(){try{const r=await fetch(asset('/progress/'+name+'/ledger.json')+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)return;const data=await r.json();if(stamp===data.updatedAt)return;stamp=data.updatedAt;
 const metrics=section.querySelector('.campaign-metrics');metrics.replaceChildren();for(const [value,label] of [[data.rendered||0,'rendered edits'],[data.reviewed||0,'visually reviewed'],['C'+String(data.selected||0).padStart(3,'0'),'selected design'],[(data.currentScore??80)+'/100','current visual score']]){const box=document.createElement('div'),b=document.createElement('b'),small=document.createElement('span');b.textContent=value;small.textContent=label;box.append(b,small);metrics.append(box);}
 section.querySelector('.campaign-note').textContent='Target: at least 100 distinct edit-and-preview candidates and 95/100 visual quality. Every score below is an individual visual assessment. Previous numerical cloth-solver passes are not counted here.';
 const sheets=[...(data.sheets||[])].reverse();const latest=section.querySelector('.campaign-latest');latest.replaceChildren();if(sheets[0]){const a=document.createElement('a'),img=document.createElement('img'),label=document.createElement('p');a.href=asset(sheets[0].url);a.target='_blank';img.src=asset(sheets[0].url)+'?v='+stamp;img.alt=sheets[0].group+' rendered comparison';img.loading='lazy';label.textContent='Latest comparison: '+sheets[0].group+' · '+sheets[0].path;a.append(img);latest.append(a,label);}
 const all=section.querySelector('.campaign-sheets');all.replaceChildren();for(const sheet of sheets){const a=document.createElement('a');a.href=asset(sheet.url);a.target='_blank';a.textContent=sheet.group+' · C'+sheet.ids.join(', C');all.append(a);}
 const reviews=section.querySelector('.campaign-reviews');reviews.replaceChildren();for(const c of [...(data.candidates||[])].reverse()){const row=document.createElement('article'),title=document.createElement('h4'),p=document.createElement('p'),link=document.createElement('a');title.textContent='C'+String(c.id).padStart(3,'0')+' · '+(c.score??'pending')+'/100 · '+c.label;p.textContent=c.review||'Rendered; awaiting individual visual review.';link.href=asset('/progress/'+name+'/c'+String(c.id).padStart(3,'0')+'-'+suffix+'/design-'+suffix+'.json');link.textContent='Editable design state +';row.append(title,p,link);reviews.append(row);}
 }catch(e){console.warn('Campaign ledger unavailable:',e.message);}}
 refresh();setInterval(refresh,5000);
}
