import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {createCharacter} from './body.js';
import {revision} from './revision.js';
// Vite's base path permits the same studio to run at / or a GitHub Pages project path.
const assetURL=(path)=>/^https?:\/\//.test(path)?path:import.meta.env.BASE_URL+path.replace(/^\/+/, '');
const params=new URLSearchParams(location.search),renderOnly=params.has('render');if(renderOnly)document.body.classList.add('render');
const viewport=document.querySelector('#viewport'),scene=new THREE.Scene();scene.background=new THREE.Color('#e9e8e4');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(renderOnly?1:Math.min(devicePixelRatio,1.5));renderer.setSize(viewport.clientWidth,viewport.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;viewport.appendChild(renderer.domElement);
const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.04).texture;scene.environmentIntensity=.36;room.dispose();pmrem.dispose();
scene.add(new THREE.HemisphereLight('#faf6ee','#b3b6b7',1.1));
const key=new THREE.DirectionalLight('#fff2df',2.0);key.position.set(-2.5,4,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-1.1,right:1.1,top:2.2,bottom:-.2,near:.1,far:10});key.shadow.bias=-.00008;key.shadow.normalBias=.001;key.shadow.radius=4;scene.add(key);
const fill=new THREE.DirectionalLight('#e8efff',.65);fill.position.set(3,2,2);scene.add(fill);const rim=new THREE.DirectionalLight('#fff8e9',1.3);rim.position.set(1.5,3,-2.5);scene.add(rim);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({color:'#58616a',opacity:.18}));floor.rotation.x=-Math.PI/2;floor.position.y=.001;floor.receiveShadow=false;scene.add(floor);
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=128;const ctx=shadowCanvas.getContext('2d'),grad=ctx.createRadialGradient(64,64,3,64,64,64);grad.addColorStop(0,'rgba(40,47,53,.23)');grad.addColorStop(.3,'rgba(40,47,53,.13)');grad.addColorStop(1,'rgba(40,47,53,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,128,128);const shadowTex=new THREE.CanvasTexture(shadowCanvas),contact=new THREE.Mesh(new THREE.PlaneGeometry(.70,.46),new THREE.MeshBasicMaterial({map:shadowTex,transparent:true,depthWrite:false}));contact.rotation.x=-Math.PI/2;contact.position.set(0,.003,.04);scene.add(contact);
const {root,head,materials}=createCharacter();scene.add(root);root.updateMatrixWorld(true);let exportedRoot=null,activeRoot=root;
const camera=new THREE.PerspectiveCamera(24,viewport.clientWidth/viewport.clientHeight,.01,100);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.085;controls.minDistance=.28;controls.maxDistance=6;controls.maxPolarAngle=Math.PI*.56;controls.minPolarAngle=.20;controls.autoRotateSpeed=.6;controls.target.set(0,.85,0);
let currentView='three-quarter',dirty=true;
const views={front:{dir:[0,.095,1],distance:4.40,target:[0,.86,0]},'three-quarter':{dir:[.37,.095,.93],distance:4.40,target:[0,.86,0]},side:{dir:[1,.095,.01],distance:4.40,target:[0,.86,0]},back:{dir:[0,.095,-1],distance:4.40,target:[0,.86,0]},face:{dir:[.06,.045,1],distance:.65,target:[.034,1.525,.015]}};
function setView(name){const v=views[name]||views.front;currentView=name;camera.fov=name==='face'?30:24;camera.updateProjectionMatrix();root.rotation.y=0;controls.autoRotate=false;document.querySelector('#rotate').setAttribute('aria-pressed','false');controls.target.set(...v.target);if(!renderOnly&&name!=='face')controls.target.y=.81;const aspect=viewport.clientWidth/viewport.clientHeight;const scale=name==='face'?1:Math.max(1,.53/aspect);camera.position.copy(controls.target).add(new THREE.Vector3(...v.dir).normalize().multiplyScalar(v.distance*scale*(!renderOnly&&name!=='face'?1.11:1)));camera.lookAt(controls.target);controls.update();dirty=true;document.querySelector('#view-name').textContent=name.toUpperCase();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===name));renderer.render(scene,camera);}
function stats(){let vertices=0,triangles=0,meshes=0;activeRoot.traverse(o=>{if(!o.isMesh)return;meshes++;vertices+=o.geometry.attributes.position.count;triangles+=(o.geometry.index?o.geometry.index.count:o.geometry.attributes.position.count)/3;});return {vertices,triangles,meshes,drawCalls:renderer.info.render.calls,revision,renderer:renderer.getContext().getParameter(renderer.getContext().RENDERER),bounds:new THREE.Box3().setFromObject(activeRoot).getSize(new THREE.Vector3()).toArray()};}
function toast(text){const e=document.querySelector('#toast');e.textContent=text;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),3500);}
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function exportModel(){await setModelSource('authored');const b=document.querySelector('#export');b.disabled=true;try{toast('Preparing geometry and embedded textures…');root.updateMatrixWorld(true);const data=await new GLTFExporter().parseAsync(root,{binary:true,onlyVisible:true});saveBlob(new Blob([data],{type:'model/gltf-binary'}),'campus-portrait-gpt6-astra-pro-mcp-colabdev.glb');toast('3D model exported.');return data.byteLength;}catch(e){toast('Export failed: '+e.message);throw e;}finally{b.disabled=false;}}
async function setModelSource(source){
 if(source==='exported'&&!exportedRoot){toast('Loading the saved GLB for independent inspection…');const gltf=await new GLTFLoader().loadAsync(assetURL('/exports/campus-portrait-gpt6-astra-pro-mcp-colabdev.glb')+'?v='+revision);exportedRoot=gltf.scene;exportedRoot.name='Independent exported GLB';exportedRoot.traverse(o=>{if(o.isMesh){o.castShadow=o.userData.shadow?.cast??true;o.receiveShadow=o.userData.shadow?.receive??true;for(const material of (Array.isArray(o.material)?o.material:[o.material]))for(const value of Object.values(material)){if(value?.isTexture){value.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());value.needsUpdate=true;}}}});scene.add(exportedRoot);}
 root.visible=source!=='exported';if(exportedRoot)exportedRoot.visible=source==='exported';activeRoot=source==='exported'?exportedRoot:root;document.querySelector('#model-source').value=source;document.querySelector('#wire').setAttribute('aria-pressed','false');for(const r of [root,exportedRoot])r?.traverse(o=>{if(o.isMesh)for(const material of (Array.isArray(o.material)?o.material:[o.material]))material.wireframe=false;});dirty=true;renderer.render(scene,camera);return stats();
}
document.querySelector('#model-source').onchange=e=>setModelSource(e.target.value).catch(error=>{document.querySelector('#model-source').value='authored';toast('Could not load the saved GLB: '+error.message);console.error(error);});
function capture(){renderer.render(scene,camera);renderer.domElement.toBlob(b=>{if(b)saveBlob(b,`${currentView}-gpt6-astra-pro-mcp-colabdev.png`);},'image/png');}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelector('#reset').onclick=()=>setView('three-quarter');document.querySelector('#export').onclick=()=>exportModel().catch(console.error);document.querySelector('#capture').onclick=capture;
document.querySelector('#rotate').onclick=e=>{controls.autoRotate=!controls.autoRotate;e.currentTarget.setAttribute('aria-pressed',String(controls.autoRotate));e.currentTarget.querySelector('span').textContent=controls.autoRotate?'●':'○';dirty=true;};
document.querySelector('#wire').onclick=e=>{const on=e.currentTarget.getAttribute('aria-pressed')!=='true';activeRoot.traverse(o=>{if(o.isMesh)for(const m of (Array.isArray(o.material)?o.material:[o.material]))m.wireframe=on;});e.currentTarget.setAttribute('aria-pressed',String(on));e.currentTarget.querySelector('span').textContent=on?'●':'○';dirty=true;};
document.querySelector('#quality').onchange=e=>{renderer.setPixelRatio(Number(e.target.value));resize();};
function resize(){camera.aspect=viewport.clientWidth/viewport.clientHeight;camera.updateProjectionMatrix();renderer.setSize(viewport.clientWidth,viewport.clientHeight);dirty=true;}
new ResizeObserver(resize).observe(viewport);controls.addEventListener('change',()=>dirty=true);
let revisionStamp='';async function refresh(){try{const r=await fetch(assetURL('/progress/progress.json')+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)return;const data=await r.json();if(revisionStamp===data.updatedAt)return;revisionStamp=data.updatedAt;if(data.revision>revision){sessionStorage.setItem('campus-view',currentView);location.reload();return;}document.querySelector('#score').textContent=data.score??'—';document.querySelector('#score-fill').style.width=(data.score??0)+'%';document.querySelector('#iteration-count').textContent=`${data.iterations.length} reviewed iterations`;document.querySelector('#review-note').textContent=data.status;document.querySelector('#revision').textContent='R'+String(data.revision).padStart(2,'0');const downloadGrid=document.querySelector('#download-grid');downloadGrid.replaceChildren();for(const file of data.downloads||[]){const card=document.createElement('a');card.className='download-card';card.href=assetURL(file.url);card.setAttribute('download','');const kind=document.createElement('span');kind.className='file-type';kind.textContent=file.kind;const content=document.createElement('div'),title=document.createElement('h3'),desc=document.createElement('p'),filePath=document.createElement('code');title.textContent=file.title;desc.textContent=file.description;filePath.textContent=file.path;content.append(title,desc,filePath);card.append(kind,content);downloadGrid.append(card);}
const cards=document.querySelector('#file-cards');cards.replaceChildren();for(const file of data.files||[]){const article=document.createElement('article');article.className='file-card';const a=document.createElement('a');a.href=assetURL(file.url);a.target='_blank';a.rel='noopener';if(file.image){const img=document.createElement('img');img.src=assetURL(file.image)+'?v='+encodeURIComponent(data.updatedAt);img.alt=file.title;img.loading='lazy';a.append(img);}const h=document.createElement('h3');h.textContent=file.title+' +';a.append(h);const c=document.createElement('code');c.textContent=file.path;article.append(a,c);cards.append(article);}const journal=document.querySelector('#journal');journal.replaceChildren();for(const it of [...data.iterations].reverse()){const row=document.createElement('div');row.className='journal-entry';const score=document.createElement('b');score.textContent=it.score;const detail=document.createElement('div'),title=document.createElement('h3'),p=document.createElement('p');title.textContent=`${String(it.id).padStart(2,'0')} / ${it.title}`;p.textContent=it.notes;detail.append(title,p);row.append(score,detail);journal.append(row);}}catch(e){console.warn('Progress refresh unavailable:',e.message);}}
setView(params.get('render')||sessionStorage.getItem('campus-view')||'three-quarter');document.querySelector('#loading').remove();const s=stats();document.querySelector('#mesh-stats').textContent=`${Math.round(s.triangles/1000)}K TRIANGLES · ORIGINAL GEOMETRY`;document.querySelector('#revision').textContent='R'+String(revision).padStart(2,'0');window.studio={ready:true,setView,stats,setModelSource,exportModel,capture,root,head,materials,scene,renderer,camera,controls};
let lastDraw=0;renderer.setAnimationLoop(t=>{if(document.hidden&&!renderOnly)return;controls.update();if(dirty||controls.autoRotate){renderer.render(scene,camera);dirty=false;lastDraw=t;}});if(!renderOnly){refresh();setInterval(refresh,5000);}
